# Generated by Django 6.1.1 on 2026-09-25 06:23

"""Миграция необязательных полей и подписей моделей задач.

Разрешает пустые описания и отсутствие сроков у задач и подзадач,
задает имя категории по умолчанию и подписи отдельных полей.
"""

from django.db import migrations, models


class Migration(migrations.Migration):
    """Изменить поля моделей после миграции 0001_initial."""


    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='Other', max_length=80),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='title',
            field=models.CharField(max_length=80, verbose_name='SubTask'),
        ),
        migrations.AlterField(
            model_name='task',
            name='categories',
            field=models.ManyToManyField(to='task.category', verbose_name='Categories'),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
