# Generated by Django 6.1.1 on 2026-09-27 14:37

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_alter_category_name_alter_subtask_deadline_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(django.db.models.functions.datetime.TruncDate('created_at'), models.F('title'), name='unique_task_title_per_created_date'),
        ),
    ]
